{
 "title": "EOS PTP data",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "meanPathDelay",
   "type": "timeseries",
   "description": "Mean path delay is the mean time in nanoseconds that PTP packets take to travel between PTP master and slave.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT (realLastSyncTime / 1000000000), meanPathDelay FROM ptpmondata",
     "rawQueryText": "SELECT (realLastSyncTime / 1000000000), meanPathDelay FROM ptpmondata",
     "timeColumns": [
      "(realLastSyncTime / 1000000000)"
     ]
    }
   ]
  },
  {
   "title": "Offset from Master",
   "type": "timeseries",
   "description": "PTP offset is the difference in nanoseconds between master and slave time.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT (realLastSyncTime/ 1000000000), offsetFromMaster FROM ptpmondata",
     "rawQueryText": "SELECT (realLastSyncTime/ 1000000000), offsetFromMaster FROM ptpmondata",
     "timeColumns": [ "(realLastSyncTime/ 1000000000)" ]
    }
   ]
  },
  {
   "title": "Skew",
   "type": "timeseries",
   "description": "PTP skew is the clock frequency difference between master and slave:\nRatio of master's second to local second.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT (realLastSyncTime/ 1000000000), skew FROM ptpmondata",
     "rawQueryText": "SELECT (realLastSyncTime/ 1000000000), skew FROM ptpmondata",
     "timeColumns": [ "(realLastSyncTime/ 1000000000)" ]
    }
   ]
  }
 ]
}